---
title: "Yield by POST timing"
author: "SS"
date: "11/6/2019"
output: html_document
---

install/load packages
```{r include=FALSE}
library(betareg)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(lme4)
library(car)
library(emmeans)
library(multcompView)
library(agricolae)
library(nlme)
library(lmerTest)
library(multcomp)
library(bestNormalize)
library(glmmTMB)
library(ggpubr)
library(nortest)
library(RColorBrewer)
```

read in data and adjust data frame as needed
```{r}
Data <- read.csv("Yield.csv", header=T) 
Data = Data %>%
  drop_na()
str(Data)
dim(Data)
Data$Year=as.factor(Data$Year)
Data$Siteyr=as.factor(Data$Siteyr)
Data$Block=as.factor(Data$Block)
Data$Trt=as.factor(Data$Trt)
Data$Site=as.factor(Data$Site)

#groupwiseMean(mYield~Trt, data=Data1, conf=0.95, digits=3)

Data <- subset(Data, POST!="none")
table(Data$POST)
table(droplevels(Data)$POST)
str(Data)
```

```{r}
par(mfrow=c(2, 4))
boxplot(mYield~POST*residual, subset(Data, Siteyr=="ARL18"), main="Arlington, 2018")
boxplot(mYield~POST*residual, subset(Data, Siteyr=="ARL19"), main="Arlington, 2019")
boxplot(mYield~POST*residual, subset(Data, Siteyr=="ROK18"), main="Janesville, 2018")
boxplot(mYield~POST*residual, subset(Data, Siteyr=="ROK19"), main="Janesville, 2019")
boxplot(mYield~POST*residual, subset(Data, Siteyr=="LAN18"), main="Lancaster, 2018")
boxplot(mYield~POST*residual, subset(Data, Siteyr=="LAN19"), main="Lancaster, 2019")
boxplot(mYield~POST*residual, subset(Data, Siteyr=="BRO19"), main="Brooklyn, 2019")
```

```{r}
Data1 = Data %>%
  filter(Siteyr==c("ROK19", "ROK18"))
  #filter(Siteyr==c("ROK18", "ROK19", "BRO19"))
model=lmer(mYield ~ Year*POST*residual + (1|Siteyr:Block), data=Data1)
#normality - statistical tests and graphical checks
residuals = resid(model)
shapiro.test(residuals)
pearson.test(residuals)
qqnorm(residuals); qqline(residuals, col=2)
hist(residuals,freq=F, xlab="Residuals", ylab="Frequency", main="")
#equal variance - statistical tests and graphical checks
leveneTest(mYield~POST*residual, data=Data1)
plot(model)

summary(model)
anova(model, test.statistic = "F")
interaction.plot(Data1$Year, Data1$Site, Data1$mYield, col=2:8, xlab="residual", ylab="yield")
```


```{r}
lsm <- emmeans(model, ~ POST, adjust="none", contr="pairwise")
lsm
```



```{r warning=FALSE}
cld <- CLD(lsm, adjust="none", reversed=TRUE, Letters= letters)
cld
```

```{r}
#SUBSET DATA (ARL AND LAN 18/19) WITH SITEYR RANDOM
Data1 = Data %>%
  filter(Site==c("Arlington", "Lancaster"))
model=lmer(mYield ~ Site*Year*POST*residual + (1|Siteyr/Block), data=Data1)
#normality - statistical tests and graphical checks
residuals = resid(model)
shapiro.test(residuals)
pearson.test(residuals)
qqnorm(residuals); qqline(residuals, col=2)
hist(residuals,freq=F, xlab="Residuals", ylab="Frequency", main="")
#equal variance - statistical tests and graphical checks
leveneTest(mYield~POST*residual, data=Data1)
plot(model)

summary(model)
anova(model, test.statistic = "F")

lsm <- emmeans(model, ~ POST, adjust="none", contr="pairwise")
lsm
```


```{r}
synames = c("Arlington 2018", "Arlington 2019", "Brooklyn 2019", "Lancaster 2018", "Lancaster 2019",
            "Janesville 2018", "Janesville 2019")
names(synames) = c("ARL18", "ARL19", "BRO19", "LAN18", "LAN19", "ROK18", "ROK19")

level_order = c("A", "B", "C")

ggplot(cld1, aes(x = factor(POST, level=level_order), y=emmean, label=.group, fill=POST)) +
  geom_bar(stat="identity", width = 0.6, color="black") +
  facet_grid(.~Siteyr, labeller = labeller(Siteyr=synames)) +
  geom_linerange(aes(ymin  =  lower.CL, ymax  =  upper.CL), width =  0.1, size  =  0.7) +
  theme_bw() + theme(axis.title.y = element_text(size=25, color="black"),
                     #axis.title.x = element_text(size=20, color="black", face="bold"), 
                     legend.position="bottom", legend.direction = "horizontal", legend.box = "horizontal", 
                     legend.text = element_text(color="black", size = 15), 
                     legend.title = element_blank(),
                     #plot.title =  element_text(size=35, color="black", face="bold"),
                     #axis.text.x = element_text(size=15, angle=45, hjust=1, color="black"),
                     axis.text.x = element_blank(), 
                     axis.text.y = element_text(size=15, color="black"),
                     strip.text.x = element_text(size=15, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y=expression(paste("Yield (kg ha"^"-1",")")), x="") +
  scale_fill_manual(values=c("salmon3", "cornflowerblue", "lightgoldenrod"), name="", 
                    labels=c("E POST","M POST", "L POST")) +
  geom_text(size = 8,
            nudge_x = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            nudge_y = c(350, 350, 350, 350, 350, 350, 350, 350, 350, 350, 350, 350, 350, 350, 350,
                        350, 350, 350, 350, 350, 350),
            color   = "black") + ylim(2000, 5500) +
  scale_y_continuous(breaks=c(0, 1000, 2000,3000,4000,5000)) +
  #ggtitle("Grain Yield") +
  ggsave("Yield.tiff", units="in", width=13, height=8, dpi=600)
```

```{r}
cld <- subset(cld, Siteyr!="LAN19")
cld <- subset(cld, Siteyr!="LAN18")
cld <- subset(cld, Siteyr!="ARL18")
table(cld$Siteyr)
table(droplevels(cld)$Siteyr)
str(cld)

synames2 = c("Arlington 2019", "Brooklyn 2019", "Janesville 2018", "Janesville 2019")
names(synames2) = c("ARL19", "BRO19", "ROK18", "ROK19")

level_order = c("A", "B", "C")

ggplot(cld, aes(x = factor(POST, level=level_order), y=emmean, label=.group, fill=POST)) +
  geom_bar(stat="identity", width = 0.5, color="black") +
  facet_grid (.~Siteyr, labeller = labeller(Siteyr=synames2)) +
  geom_errorbar(aes(ymin  =  lower.CL, ymax  =  upper.CL), width =  0.1, size  =  0.7) +
  theme_bw() + theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.y = element_text(size=30, color="black"),
                     #axis.title.x = element_text(size=20, color="black", face="bold"), 
                     legend.position="bottom", legend.direction = "horizontal", legend.box = "horizontal", 
                     legend.text = element_text(color="black", size = 25), 
                     legend.title = element_blank(),
                     #plot.title =  element_text(size=35, color="black", face="bold"),
                     #axis.text.x = element_text(size=15, angle=45, hjust=1, color="black"),
                     axis.text.x = element_blank(), 
                     axis.text.y = element_text(size=15, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y=expression(paste("Yield (kg ha"^"-1",")")), x="") +
  scale_fill_manual(values=c("#C5050C", "#646569", "#282728"), name="", 
                    labels=c("EPOST","MPOST", "LPOST")) +
  geom_text(size = 10,
            nudge_x = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
            nudge_y = c(440, 440, 440, 440, 440, 440, 440, 440, 440, 440, 440, 440),
            color   = "black") + ylim(2000, 5700) +
  scale_y_continuous(breaks=c(0, 1000, 2000,3000,4000,5000)) +
  ggtitle("Soybean Grain Yield") +
  ggsave("YieldV2.tiff", units="in", width=27, height=6, dpi=600)
```

```{r}
cld1 = cld %>%
  filter(Siteyr=="ROK19")

level_order = c("A", "B", "C")

ggplot(cld1, aes(x = factor(POST, level=level_order), y=emmean, label=.group, fill=POST)) +
  geom_bar(stat="identity", width = 0.5, color="black") +
  #facet_grid (.~Siteyr, labeller = labeller(Siteyr=synames2)) +
  geom_errorbar(aes(ymin  =  lower.CL, ymax  =  upper.CL), width =  0.1, size  =  0.7) +
  theme_bw() + theme(plot.title = element_text(hjust=0.5, size=35, face="bold"),
                     axis.title.y = element_text(size=30, color="black"),
                     #axis.title.x = element_text(size=20, color="black", face="bold"), 
                     legend.position="bottom", legend.direction = "horizontal", legend.box = "horizontal", 
                     legend.text = element_text(color="black", size = 25), 
                     legend.title = element_blank(),
                     #plot.title =  element_text(size=35, color="black", face="bold"),
                     #axis.text.x = element_text(size=15, angle=45, hjust=1, color="black"),
                     axis.text.x = element_blank(), 
                     axis.text.y = element_text(size=15, color="black"),
                     strip.text.x = element_text(size=25, color="black", face="bold"),
                     strip.text = element_text(size=13), 
                     panel.background =element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y=expression(paste("Yield (kg ha"^"-1",")")), x="") +
  scale_fill_manual(values=c("#C5050C", "#646569", "#282728"), name="", 
                    labels=c("EPOST","MPOST", "LPOST")) +
  geom_text(size = 10,
            nudge_x = c(0, 0, 0),
            nudge_y = c(440, 440, 440),
            color   = "black") + ylim(2000, 5700) +
  scale_y_continuous(breaks=c(0, 1000, 2000,3000,4000,5000)) +
  #ggtitle("Soybean Grain Yield") +
  ggsave("YieldV2 ROK19.tiff", units="in", width=6, height=8, dpi=600)
```


```{r}
Data2 = Data %>%
  filter(Siteyr=="ROK19")
model=lmer(mYield ~ POST*residual + (1|Block), data=Data2)
anova(model, test.statistic = "F")
#interaction.plot(Data$POST, Data$Siteyr, Data$mYield, col=2:8, xlab="residual", ylab="yield")

lsm <- emmeans(model, ~ POST, adjust="none", contr="pairwise")
lsm
cld <- CLD(lsm, adjust="none", reversed=TRUE, Letters= letters)
cld

model=lm(mYield~POST*residual, data=Data2)
LSD.test(model, "POST", alpha=0.05, p.adj="none", console=TRUE)
```

