---
title: "control_post"
author: "Sarah Striegel"
date: "2/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = TRUE,
  warning = TRUE,
  error = TRUE)
```


```{r}
library(tidyverse)
library(glmmTMB)
library(emmeans)
library(car)
```

```{r}
control <- read_csv("Visual control.csv")
```

```{r}
control1 <- control %>% 
  mutate_if(is.character, as.factor) %>% 
  filter(!Trtdes %in% c("Check", "PRE")) %>% 
  mutate(
    Block = as.factor(Block),
    Year = as.factor(Year),
    Trt = as.factor(Trt),
    control = control/100) %>% 
  janitor::clean_names() %>% 
  dplyr::select(site, year, siteyr, block, trt, trtdes, post, residual, control) %>% 
  mutate(residual = fct_recode(residual, "no" = "none"),
         post = fct_recode(post, "no" = "none"))
```


```{r}
leveneTest(control ~ siteyr, data = control1)
```


```{r}
control1 %>% 
  group_by(trtdes) %>% 
  summarise(min = min(control), max = max(control))
```

```{r}
control2 <- control1 %>% 
  nest(year, siteyr, block, trt, trtdes, post, residual, control)
```

```{r beta-function}
beta_model <- function(df) {
  model = glmmTMB(control ~ post * residual + (1|year:block), 
                beta_family(link="logit"),
                REML = FALSE, data = df)
}
```


```{r model, warning = FALSE}
control3 <- control2 %>% 
  mutate(model = map(data, beta_model))
```



```{r anova}
control4 <- control3 %>% 
    mutate(anova = map(model, glmmTMB:::Anova.glmmTMB))
```


```{r check-anova}
control4 %>% 
  filter(site == "Brooklyn") %>% 
  unnest(anova)
# You can check your ANOVA by filtering
```


```{r emmeans_function}
control5 <- control4 %>% 
  mutate(
    emmeans = pmap(
      .l = list(
        object = model, 
        list(specs = ~ post | residual),
        type="response",
#        cont="pairwise", 
        adjust="none"
      ),
      .f = emmeans
    )
  ) 
```



```{r check-emmeans}
# full data frame with all means and CIs 
control5 %>% 
  mutate(emm2 = map(emmeans, data.frame)) %>% 
  unnest(emm2) #
#You can filter and make a data frame for each population and rate
```


```{r cld-function}
cld_function <- function(emmeans) {
  if(requireNamespace("multcomp")) {
    multcomp::cld(emmeans, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE)
}
}
```


```{r cld}
control6 <- control5 %>% 
  mutate(cld = map(emmeans, cld_function))
```


```{r}
# here is similar to emmeans but you have letters
control7 <- control6 %>% 
  unnest(cld)
# You can also filter and make specific data frames
control7
```



```{r}
control7 %>% 
  ggplot(aes(x = post, y = response)) +
  geom_point() +
#  geom_label(aes(label = .group), parse = TRUE, # somthing is wrong with geom_text
#            nudge_x = 0,
#            nudge_y = -0.3) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
  facet_grid(residual ~ site, scales = "free") +
  coord_flip() +
#  scale_x_reordered() +
  scale_y_continuous("% control", limits = c(0, 1.03),
                     labels = scales::label_number(scale = 100)) +
  theme_bw()
# this is how you reorder by high to low. Notice that all rates follow same pattern.
```
