---
title: "Figure_waterhemp"
author: "Sarah Striegel"
date: "2/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = TRUE,
  warning = TRUE,
  error = TRUE)
```


```{r}
library(tidyverse)
library(tidytext)
library(patchwork)
library(gridExtra)
library(ggthemes)
library(extrafont)
library(ggtext)
library(rlang)
library(sysfonts)
```


```{r janesville}
brook_yield <- yield7 %>% 
  filter(site == "Brooklyn")

brook_control <- control7 %>% 
  filter(site == "Brooklyn")

brook_biomass <- biomass7 %>% 
  filter(site == "Brooklyn")

brook_density <- density7 %>% 
  filter(site == "Brooklyn")
options(scipen = 999) # avoid exponential numbers
brook_seed <- seed7 %>% 
  filter(site == "Brooklyn") %>% 
  mutate_at(c("lower.CL", "upper.CL"), round)
```

```{r}
element_textbox_highlight <- function(..., hi.labels = NULL, hi.fill = NULL,
                                      hi.col = NULL, hi.box.col = NULL, hi.family = NULL) {
  structure(
    c(element_textbox(...),
      list(hi.labels = hi.labels, hi.fill = hi.fill, hi.col = hi.col, hi.box.col = hi.box.col, hi.family = hi.family)
    ),
    class = c("element_textbox_highlight", "element_textbox", "element_text", "element")
  )
}
element_grob.element_textbox_highlight <- function(element, label = "", ...) {
  if (label %in% element$hi.labels) {
    element$fill <- element$hi.fill %||% element$fill
    element$colour <- element$hi.col %||% element$colour
    element$box.colour <- element$hi.box.col %||% element$box.colour
    element$family <- element$hi.family %||% element$family
  }
  NextMethod()
}
```


```{r brook-control}
b1 <- brook_control %>% 
  mutate(post = fct_recode(post,
                           "Early POST" = "A",
                           "Mid POST" = "B",
                           "Late POST" = "C")#,
         #residual = fct_recode#(residual,
                               #"With residual" = "yes",
                               #"No residual" = "no")
                               ) %>% 
#  group_by(post, residual) %>% 
#  mutate(post = reorder_within(post, by = response, within = residual)) %>% 
  ggplot(aes(x = post, y = response, color = post)) +
  geom_point(size = 2) +
  geom_jitter(data = control1 %>% 
               filter(site == "Brooklyn") %>% 
               mutate(post = fct_recode(post,
                           "Early POST" = "A",
                           "Mid POST" = "B",
                           "Late POST" = "C")#,
                      #residual = fct_recode(residual,
                               #"With residual" = "yes",
                               #"No residual" = "no")
                      ), aes(y = control), 
              alpha = 0.1) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
  #facet_grid(~ residual) +
  coord_flip() +
  theme_test() +
  scale_color_brewer(palette = "Set1") +
  labs(x = "", y = "% waterhemp control", title = "") +
  scale_y_continuous(limits = c(0, 1.03),
                     breaks = c(0, 0.25, 0.5, 0.75, 1.0),
                     labels = scales::label_number(scale = 100)) +
  theme(axis.text.y = element_text(size=10, face = "bold"),
        axis.text.x = element_text(size=10),
        legend.position = "none",
    strip.text = element_textbox_highlight(
      size = 12, face = "bold",
      fill = "#c5050c", box.color = "#c5050c", color = "white",
      halign = .5, linetype = 1, r = unit(0, "pt"), width = unit(1, "npc"),
      padding = margin(2, 0, 1, 0), margin = margin(0, 1, 0, 1),
      hi.labels = "With residual", hi.family = "",
      hi.fill = "#0479a8", hi.box.col = "#0479a8", hi.col = "white"))
```


```{r}
b2 <- brook_biomass %>% 
  mutate(post = fct_recode(post,
                           "Early POST" = "A",
                           "Mid POST" = "B",
                           "Late POST" = "C")) %>% 
  ggplot(aes(x = post, y = response, color = post)) +
  geom_point(size = 2) +
  geom_jitter(data = biomass1 %>% 
               filter(site == "Brooklyn") %>% 
               mutate(post = fct_recode(post,
                           "Early POST" = "A",
                           "Mid POST" = "B",
                           "Late POST" = "C"),
                      residual = fct_recode(residual,
                               "With residual" = "yes",
                               "No residual" = "no")), aes(y = biored), 
              alpha = 0.1) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
  coord_flip() +
  labs(x = "", y = "% waterhemp biomass reduction", title = "") +
  scale_y_continuous(limits = c(0, 1.03),
                     breaks = c(0, 0.25, 0.5, 0.75, 1.0),
                     labels = scales::label_number(scale = 100)) +
  theme_test() +
  scale_color_brewer(palette = "Set1") +
  theme(axis.text.y = element_text(size=10, face = "bold"),
        axis.text.x = element_text(size=10),
        legend.position = "none")
```


```{r}
b3 <- brook_density %>% 
    mutate(post = fct_recode(post,
                           "Early POST" = "A",
                           "Mid POST" = "B",
                           "Late POST" = "C"),
         residual = fct_recode(residual,
                               "With residual" = "yes",
                               "No residual" = "no")) %>% 
  ggplot(aes(x = post, y = response, color = post)) +
  geom_point(size = 2) +
  geom_jitter(data = density1 %>% 
               filter(site == "Brooklyn") %>% 
               mutate(post = fct_recode(post,
                           "Early POST" = "A",
                           "Mid POST" = "B",
                           "Late POST" = "C"),
                      residual = fct_recode(residual,
                               "With residual" = "yes",
                               "No residual" = "no")), aes(y = dens_red), 
              alpha = 0.1) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
  facet_grid(~ residual) +
  coord_flip() +
  theme_test() +
  scale_color_brewer(palette = "Set1") + 
  labs(x = "", y = "% waterhemp density reduction", title = "") +
  scale_y_continuous(limits = c(0, 1.03),
                     breaks = c(0, 0.25, 0.5, 0.75, 1.0),
                     labels = scales::label_number(scale = 100)) +
   theme(axis.text.y = element_text(size=10, face = "bold"),
        axis.text.x = element_text(size=10),
            strip.text = element_textbox_highlight(
      size = 12, face = "bold",
      fill = "#c5050c", box.color = "#c5050c", color = "white",
      halign = .5, linetype = 1, r = unit(0, "pt"), width = unit(1, "npc"),
      padding = margin(2, 0, 1, 0), margin = margin(0, 1, 0, 1),
      hi.labels = "With residual", hi.family = "",
      hi.fill = "#0479a8", hi.box.col = "#0479a8", hi.col = "white"),
         legend.position = "none")
```


```{r jan yield}
b4 <- brook_yield %>% 
    mutate(post = fct_recode(post,
                           "Early POST" = "A",
                           "Mid POST" = "B",
                           "Late POST" = "C")) %>% 
  ggplot(aes(x = post, y = emmean, color = post)) +
  geom_point(size = 2) +
  geom_jitter(data = yield1 %>% 
               filter(site == "Brooklyn") %>% 
               mutate(post = fct_recode(post,
                           "Early POST" = "A",
                           "Mid POST" = "B",
                           "Late POST" = "C")), aes(y = m_yield), alpha = 0.1) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
  coord_flip() +
  theme_test() +
  scale_color_brewer(palette = "Set1") +
  labs(x = "", y = expression(paste("Soybean yield (kg ha"^"-1",")")),
       title = "") +
    scale_y_continuous(limits = c(0, 4500),
                       breaks = c(0, 1500, 3000, 4500)) +
  theme(axis.text.y = element_text(size=10, face = "bold"),
        axis.text.x = element_text(size=10),
        legend.position = "none")
```

```{r}
b5 <- brook_seed %>% 
  mutate(post = fct_recode(post,
                           "Early POST" = "A",
                           "Mid POST" = "B",
                           "Late POST" = "C"),
         residual = fct_recode(residual,
                               "With residual" = "yes",
                               "No residual" = "no")) %>% 
  ggplot(aes(x = post, y = rate, color = post)) +
  geom_point(size = 2) +
  geom_jitter(data = seed1 %>% 
               filter(site == "Brooklyn") %>% 
               mutate(post = fct_recode(post,
                           "Early POST" = "A",
                           "Mid POST" = "B",
                           "Late POST" = "C"),
                      residual = fct_recode(residual,
                               "With residual" = "yes",
                               "No residual" = "no")), aes(y = mseed), alpha = 0.1) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
  facet_grid(~ residual) +
  coord_flip() +
  theme_test() +
  scale_color_brewer(palette = "Set1") +
  labs(x = "", y = "Number of seeds (×1000)",
       title = "") +
  scale_y_continuous(labels = scales::label_number(scale = 1/1000, 
                                                  acaccuracy = 1)) +
  theme(axis.text.y = element_text(size=10, face = "bold"),
         axis.text.x = element_text(size=10),
             strip.text = element_textbox_highlight(
      size = 12, face = "bold",
      fill = "#c5050c", box.color = "#c5050c", color = "white",
      halign = .5, linetype = 1, r = unit(0, "pt"), width = unit(1, "npc"),
      padding = margin(2, 0, 1, 0), margin = margin(0, 1, 0, 1),
      hi.labels = "With residual", hi.family = "",
      hi.fill = "#0479a8", hi.box.col = "#0479a8", hi.col = "white"),
        legend.position = "none")
```

```{r}
label <- "50% emergence ratio = 1 <br> *P* = 0.34"

b6 <- ggplot(brook_data, aes(x=doy, y=(emergence*100), color=trt, 
                       linetype = trt)) +
  annotate("rect", xmin = 135, xmax = 152, ymin = 0, ymax = 120, 
           alpha = .1, fill = "yellow") +
  annotate("rect", xmin = 152, xmax = 182, ymin = 0, ymax = 120, 
           alpha = .1, fill = "green") +
  annotate("rect", xmin = 182, xmax = 213, ymin = 0, ymax = 120, 
           alpha = .1, fill = "blue") +
  annotate("rect", xmin = 213, xmax = 215, ymin = 0, ymax = 120, 
           alpha = .1, fill = "grey") +
  annotate("text", x = 143, y = 115, label = "May",
           alpha = .5, fill = "black") +
  annotate("text", x = 167, y = 115, label = "June",
           alpha = .5, fill = "black") +
  annotate("text", x = 197, y = 115, label = "July",
           alpha = .5, fill = "black") +
  geom_jitter(size=2, alpha = 0.1) + 
  geom_line(data=nd, aes(x=doy, y=(p*100)), size=1) +
  theme_test() +
  theme(axis.text.y = element_text(size=10),
         axis.text.x = element_text(size=10),
        legend.position = c(0.8, 0.2),
        legend.background = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_blank()) +
  labs(y="% waterhemp emergence", x="Day of year", 
       title = "") +
  geom_richtext(x = 150, y = 90, show.legend = FALSE, size = 2,
                    label = label, alpha = 0.5, color = "black",
                width = unit(5, "lines"),
                stat = "unique") +
  scale_x_continuous(limits=c(135,215)) +
  scale_y_continuous(breaks=c(0., 25, 50, 75, 100)) +
  scale_fill_manual(values = c("#494949", "#c5050c")) + 
  scale_color_manual(values = c("#494949", "#c5050c")) 
```



```{r}
library(lubridate)
day <- ymd(20180801)
lubridate::yday(day)
```


```{r}
library(maps)
library(ggmap)
library(ggrepel)
library(grid)
library(mapdata)
library(maptools)
library(stringr)
library(dplyr)
library(ggsn)
```

```{r}
states = map_data("state")
df <- subset(states, region =="wisconsin")
```

```{r}
counties <- map_data("county")
county <- subset(counties, region =="wisconsin")
county 
```


```{r}
b7 <- ggplot(data = county, mapping = aes(x = long, y = lat, group = group)) + 
#  coord_fixed(ratio = 1, expand = TRUE, clip = on) +
  geom_polygon(color = "grey80", fill = "white") +
  geom_polygon(data = county %>% 
                 filter(subregion == "dane"), aes(fill = subregion),
               show.legend = FALSE, fill = "#c5050c") +
  geom_point(aes(x = -89.36, y = 42.92), size = 0.5) +
  annotate("text", x= -88.5, y = 47, label = "Brooklyn, Dane County, WI",
           size = 2) +
  theme_test() +
#  labs(title = "Rock County - Lancaster, WI") +
  coord_map("orthographic") +
  labs(x ="", y = "") +
#  north(df, location = 'topleft', symbol = 3, anchor = c(x = -87.5, y = 47)) +
#  scalebar(df, dist = 50, dist_unit="km", model = 'International', 
#           location = "bottomleft", transform = TRUE) +
  theme(axis.text.y = element_text(size=10),
         axis.text.x = element_text(size=10))
```








```{r figure-map}
bc <- {(b7 / b6) | (b1 / b3) | (b5 / b4)} +
  plot_layout(byrow = TRUE) &
  plot_annotation(tag_levels = 'A', 
  title = 'Waterhemp biology and management in Brooklyn, Dane County',
  subtitle = "Waterhemp is a troublesome weed in Southern Wisconsin. Data is presented from 2019",
  theme = theme(plot.title = element_text(size = 18))) & 
  theme(plot.title = element_text("serif"))
  ggsave('brooklyn_1.pdf',  height = 6, width = 12, bc) 
```
