---
title: "SB13 visual control by POST timing"
author: "ss"
date: "9/25/2019"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

install/load packages
```{r include=FALSE}
library(betareg)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(lme4)
library(car)
library(emmeans)
library(multcompView)
library(agricolae)
library(nlme)
library(lmerTest)
library(multcomp)
library(bestNormalize)
library(glmmTMB)
library(rcompanion)
library(Matrix)
library(TMB)
library(RCurl)
library(kableExtra)
```

read in data and adjust data frame as needed
```{r}
Data <- read.csv("Visual control.csv", header=T)
str(Data)
dim(Data)
Data$Year=as.factor(Data$Year)
Data$Siteyr=as.factor(Data$Siteyr)
Data$Block=as.factor(Data$Block)
Data$Trt=as.factor(Data$Trt)
Data$Site=as.factor(Data$Site)
Data$POST=as.factor(Data$POST)
Data$residual=as.factor(Data$residual)

Data = Data %>%
  #drop_na() %>%
  mutate(overall = Overall/100) %>%
  mutate(ambel = AMBEL/100) %>%
  mutate(ambtr = AMBTR/100) %>%
  mutate(amatu = AMATU/100) %>%
  mutate(amare = AMARE/100) %>%
  mutate(other = Other/100) %>%
  mutate(cheal = CHEAL/100) %>%
  mutate(abuth = ABUTH/100) %>%
  mutate(poa = Poaceae/100)

#groupwiseMean(ambtr~Trt|Siteyr, data=Data, conf=0.95, digits=3)

Data <- subset(Data, POST!="none")
table(Data$POST)
table(droplevels(Data)$POST)
str(Data)
```

```{r Overall Control}
#WITH SITE-YR FIXED
model=glmmTMB(overall ~ Siteyr*POST*residual + (1|Siteyr:Block), data=Data, beta_family(link="logit"))
leveneTest(overall~POST*residual, data=Data)

summary(model)
glmmTMB:::Anova.glmmTMB(model, test.statistic = "Chisq", type = "II")
interaction.plot(Data$residual, Data$POST, Data$overall, col=2:4, xlab="residual", ylab="overall control")
interaction.plot(Data$POST, Data$Siteyr, Data$overall, col=2:8, xlab="POST", ylab="overall control")

lsm <- emmeans(model, ~ POST*residual|Siteyr, type="response", adjust="none", contr="pairwise")
lsm
cld <- CLD(lsm, adjust="none", reversed=TRUE, Letters= letters)
cld

#WITH SUBSETTED DATASET (ARL & LAN 18/19) AND SITEYR RANDOM
Data1 = Data %>%
  filter(Site==c("Arlington", "Lancaster"))
model=glmmTMB(overall ~ POST*residual + (1|Siteyr/Block), data=Data1, beta_family(link="logit"))
leveneTest(overall~POST*residual, data=Data1)

summary(model)
glmmTMB:::Anova.glmmTMB(model, test.statistic = "Chisq", type = "II")

lsm <- emmeans(model, ~ POST, type="response", adjust="none", contr="pairwise")
lsm
```

```{r CHEAL}
#WITH SITE-YR FIXED
model.2=glmmTMB(cheal ~ Siteyr*POST*residual + (1|Siteyr:Block), data=Data, beta_family(link="logit"))
leveneTest(cheal~POST*residual, data=Data)

summary(model.2)
glmmTMB:::Anova.glmmTMB(model.2, test.statistic = "Chisq", type = "II")

lsm2 <- emmeans(model.2, ~ POST*residual | Siteyr, type="response", adjust="none", contr="pairwise")
lsm2

#WITH SUBSETTED DATASET (ARL & LAN 18/19) AND SITEYR RANDOM
model.2=glmmTMB(cheal ~ Site*Year*POST*residual + (1|Siteyr/Block), data=Data1, beta_family(link="logit"))
leveneTest(cheal~POST*residual, data=Data1)

summary(model.2)
glmmTMB:::Anova.glmmTMB(model.2, test.statistic = "Chisq", type = "II")

lsm2 <- emmeans(model.2, ~ POST, type="response", adjust="none", contr="pairwise")
lsm2
```

```{r AMBEL}
#WITH SITE-YR FIXED
model.3=glmmTMB(ambel ~ Siteyr*POST*residual + (1|Siteyr:Block), data=Data, beta_family(link="logit"))
leveneTest(ambel~POST*residual, data=Data)

summary(model.3)
glmmTMB:::Anova.glmmTMB(model.3, test.statistic = "Chisq", type = "II")
interaction.plot(Data$POST, Data$Siteyr, Data$ambel, col=2:8, xlab="POST", ylab="ambel control")

lsm3 <- emmeans(model.3, ~ POST*residual | Siteyr, type="response", adjust="none", contr="pairwise")
lsm3
cld3 <- CLD(lsm3, adjust="none", reversed=TRUE, Letters= letters)
cld3

#WITH SUBSETTED DATASET (ARL 18/19 & LAN 18) AND SITEYR RANDOM
Data2 = Data1 %>%
  filter(Siteyr==c("ARL18", "ARL19", "LAN18"))
model.3=glmmTMB(ambel ~ POST*residual + (1|Siteyr/Block), data=Data2, beta_family(link="logit"))
leveneTest(ambel~POST*residual, data=Data2)

summary(model.3)
glmmTMB:::Anova.glmmTMB(model.3, test.statistic = "Chisq", type = "II")

lsm3 <- emmeans(model.3, ~ POST, type="response", adjust="none", contr="pairwise")
lsm3
```

```{r ABUTH}
#WITH SITE-YR FIXED
model.4=glmmTMB(abuth ~ Siteyr*POST*residual + (1|Siteyr:Block), data=Data, beta_family(link="logit"))
leveneTest(abuth~POST*residual, data=Data)

summary(model.4)
glmmTMB:::Anova.glmmTMB(model.4, test.statistic = "Chisq", type = "II")

lsm4 <- emmeans(model.4, ~ POST*residual | Siteyr, type="response", adjust="none", contr="pairwise")
lsm4

#WITH SUBSETTED DATASET (ARL & LAN 18/19) AND SITEYR RANDOM
model.4=glmmTMB(abuth ~ POST*residual + (1|Siteyr/Block), data=Data1, beta_family(link="logit"))
leveneTest(abuth~POST*residual, data=Data1)

summary(model.4)
glmmTMB:::Anova.glmmTMB(model.4, test.statistic = "Chisq", type = "II")

lsm4 <- emmeans(model.4, ~ POST, type="response", adjust="none", contr="pairwise")
lsm4
```

```{r Poaceae}
#WITH SITE-YR FIXED
model.5=glmmTMB(poa ~ Siteyr*POST*residual + (1|Siteyr:Block), data=Data, beta_family(link="logit"))
leveneTest(poa~POST*residual, data=Data)

summary(model.5)
glmmTMB:::Anova.glmmTMB(model.5, test.statistic = "Chisq", type = "II")
interaction.plot(Data$residual, Data$POST, Data$poa, col=2:4, xlab="residual", ylab="grass control")
interaction.plot(Data$POST, Data$Siteyr, Data$poa, col=2:8, xlab="POST", ylab="grass control")

lsm5 <- emmeans(model.5, ~ POST*residual | Siteyr, type="response", adjust="none", contr="pairwise")
lsm5
cld5 <- CLD(lsm5, adjust="none", reversed=TRUE, Letters= letters)
cld5

#WITH SUBSETTED DATASET (ARL & LAN 18/19) AND SITEYR RANDOM
model.5=glmmTMB(poa ~ Site*Year*POST*residual + (1|Siteyr/Block), data=Data1, beta_family(link="logit"))
leveneTest(poa~POST*residual, data=Data1)

summary(model.5)
glmmTMB:::Anova.glmmTMB(model.5, test.statistic = "Chisq", type = "II")

lsm5 <- emmeans(model.5, ~ POST, type="response", adjust="none", contr="pairwise")
lsm5
```

```{r AMBTR}
#WITH SITE-YR FIXED
dataROK = Data %>%
  filter(Site=="Janesville")
model.6=glmmTMB(ambtr ~ Year*POST*residual + (1|Year:Block), data=dataROK, beta_family(link="logit"))
leveneTest(ambtr~POST*residual, data=Data)

summary(model.6)
glmmTMB:::Anova.glmmTMB(model.6, test.statistic = "Chisq", type = "II")
interaction.plot(Data$POST, Data$Siteyr, Data$ambtr, col=2:8, xlab="POST", ylab="ambtr control")

lsm6 <- emmeans(model.6, ~ POST*residual | Siteyr, type="response", adjust="none", contr="pairwise")
lsm6
cld6 <- CLD(lsm6, adjust="none", reversed=TRUE, Letters= letters)
cld6
```

```{r AMATU}
#WITH SITE-YR FIXED
model.7=glmmTMB(amatu ~ Siteyr*POST*residual + (1|Siteyr:Block), data=Data, beta_family(link="logit"))
leveneTest(amatu~POST*residual, data=Data)

summary(model.7)
glmmTMB:::Anova.glmmTMB(model.7, test.statistic = "Chisq", type = "II")

lsm7 <- emmeans(model.7, ~ POST*residual | Siteyr, type="response", adjust="none", contr="pairwise")
lsm7
cld7 <- CLD(lsm7, adjust="none", reversed=TRUE, Letters= letters)
cld7

#WITH SUBSETTED DATASET (LAN 18/19) AND SITEYR RANDOM
Data3 = Data %>%
  filter(Site=="Lancaster")
model.7=glmmTMB(amatu ~ Year*POST*residual + (1|Siteyr/Block), data=Data3, beta_family(link="logit"))
leveneTest(amatu~POST*residual, data=Data3)

summary(model.7)
glmmTMB:::Anova.glmmTMB(model.7, test.statistic = "Chisq", type = "II")

lsm7 <- emmeans(model.7, ~ POST*residual, type="response", adjust="none", contr="pairwise")
lsm7
cld7 <- CLD(lsm7, adjust="none", reversed=TRUE, Letters= letters)
cld7

model=lm(amatu~POST*residual, data=Data3)
LSD.test(model, "POST", alpha=0.05, p.adj="none", console=TRUE)
```

```{r AMARE}
#WITH SITE-YR FIXED
model.8=glmmTMB(amare ~ Siteyr*POST*residual + (1|Siteyr:Block), data=Data, beta_family(link="logit"))
leveneTest(amare~POST*residual, data=Data)

summary(model.8)
glmmTMB:::Anova.glmmTMB(model.8, test.statistic = "Chisq", type = "II")

lsm8 <- emmeans(model.8, ~ POST*residual | Siteyr, type="response", adjust="none", contr="pairwise")
lsm8
```

```{r other}
#WITH SITE-YR FIXED
model.9=glmmTMB(other ~ Siteyr*POST*residual + (1|Siteyr:Block), data=Data, beta_family(link="logit"))
leveneTest(other~POST*residual, data=Data)

summary(model.9)
glmmTMB:::Anova.glmmTMB(model.9, test.statistic = "Chisq", type = "II")

lsm9 <- emmeans(model.9, ~ POST*residual | Siteyr, type="response", adjust="none", contr="pairwise")
lsm9
```

```{r Ind}
data2 = Data %>%
  filter(Siteyr=="BRO19")
modelBYSY=glmmTMB(ambtr ~ POST*residual + (1|Block), data=data2, beta_family(link="logit"))
#leveneTest(overall~POST*residual, data=Data)

summary(modelBYSY)
glmmTMB:::Anova.glmmTMB(modelBYSY, test.statistic = "Chisq", type = "II")
#interaction.plot(Data$residual, Data$POST, Data$overall, col=2:4, xlab="residual", ylab="overall control")
#interaction.plot(Data$POST, Data$Siteyr, Data$overall, col=2:8, xlab="POST", ylab="overall control")

lsmSYT <- emmeans(modelBYSY, ~ residual, type="response", adjust="none", contr="pairwise")
lsmSYT
cldSY <- CLD(lsmSYT, adjust="none", reversed=TRUE, Letters= letters)
cldSY

model=lm(amatu~POST*residual, data=data2)
LSD.test(model, "POST", alpha=0.05, p.adj="none", console=TRUE)
```
