---
title: "seed_fecundy"
author: "Maxwel Coura Oliveira"
date: "2/4/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = TRUE,
  warning = TRUE,
  error = TRUE)
```


```{r load-package}
library(tidyverse)
library(lme4)
library(emmeans)
library(car)
library(lmerTest)
```


```{r load-data}
seed <- read_csv("Weed seed fecundity and viability.csv") 
```



```{r clean-data}
seed1 <- seed %>% 
  janitor::clean_names() %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(
    block = as.factor(block),
    year = as.factor(year),
    trt = as.factor(trt)) %>% 
  filter(!trt %in% c("1", "2")) %>% 
  dplyr::select(site, year, block, trt, trt_des, post, residual, mseed) %>% 
  mutate(mseed = round(mseed, 0))
```

```{r nest}
seed2 <- seed1 %>% 
  nest(-site)
```



```{r function}
seed_model <- function(df) {
  glmmTMB(mseed ~ post * residual + (1|year:block), 
       family=poisson(link="log"),
       data=df)
}
```


```{r model, warning = FALSE}
seed3 <- seed2 %>% 
  mutate(model = map(data, seed_model))
```


```{r anova}
seed4 <- seed3 %>% 
    mutate(anova = map(model, glmmTMB:::Anova.glmmTMB))
```


```{r check-anova}
seed4 %>% 
  filter(site == "Brooklyn") %>% 
  unnest(anova)
# You can check your ANOVA by filtering for each pop and rate
```


```{r emmeans_function}
seed5 <- seed4 %>% 
  mutate(
    emmeans = pmap(
      .l = list(
        object = model, 
        list(specs = ~ post | residual),
        type="response",
#        cont="pairwise", 
        adjust="none"
      ),
      .f = emmeans
    )
  ) 
```


```{r check-emmeans}
# full data frame with all means and CIs 
seed5 %>% 
  mutate(emm2 = map(emmeans, data.frame)) %>% 
  unnest(emm2) 
#
#You can filter and make a data frame for each population and rate
```


```{r cld-function}
cld_function <- function(emmeans) {
  if(requireNamespace("multcomp")) {
    multcomp::cld(emmeans, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE)
}
}
```


```{r cld}
seed6 <- seed5 %>% 
  mutate(cld = map(emmeans, cld_function))
```


```{r}
# here is similar to emmeans but you have letters
seed7 <- seed6 %>% 
  unnest(cld) %>% 
  mutate(rate = round(rate, 0)) %>% 
  mutate(upper.CL = if_else(upper.CL == Inf, 0, upper.CL))
# You can also filter and make specific data frames
seed7
```


```{r}
seed7 %>% 
  ggplot(aes(x = post, y = rate, color = residual)) +
  geom_point() +
#  geom_label(aes(label = .group), parse = TRUE, # somthing is wrong with geom_text
#            nudge_x = 0,
#            nudge_y = -0.3) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
  facet_grid(residual ~ site) +
#  coord_flip() +
#  scale_x_reordered() +
  scale_y_continuous("seed production", limits = c(0, 350000),
                     labels = scales::number_format(scale = 1)) +
  theme_bw()
# this is how you reorder by high to low. Notice that all rates follow same pattern.
```