---
title: "yield_post"
author: "Maxwel Coura Oliveira"
date: "2/4/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = TRUE,
  warning = TRUE,
  error = TRUE)
```


```{r load-package}
library(tidyverse)
library(lme4)
library(emmeans)
library(car)
library(lmerTest)
```


```{r load-data}
yield <- read_csv("Yield.csv") 
```



```{r clean-data}
yield1 <- yield %>% 
  janitor::clean_names() %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(
    block = as.factor(block),
    year = as.factor(year),
    trt = as.factor(trt)) %>% 
  filter(!trt %in% c("1", "2")) %>% 
  select(site, year, block, trt, trt_des, post, residual, m_yield)
```

```{r nesting}
yield2 <- yield1 %>% 
  nest(-site)
```


  
```{r function}
yield_model <- function(df) {
  lmer(m_yield ~ post * residual + (1|year:block), REML = TRUE,
       data=df)
}
```


```{r model, warning = FALSE}
yield3 <- yield2 %>% 
  mutate(model = map(data, yield_model))
```


```{r anova}
yield4 <- yield3 %>% 
    mutate(anova = map(model, anova))
```


```{r check-anova}
yield4 %>% 
  filter(site == "Arlington") %>% 
  unnest(anova)
# You can check your ANOVA by filtering for each pop and rate
```




```{r emmeans_function}
yield5 <- yield4 %>% 
  mutate(
    emmeans = pmap(
      .l = list(
        object = model, 
        list(specs = ~ post),
#        type="response",
#        cont="pairwise", 
        adjust="none"
      ),
      .f = emmeans
    )
  ) 
```

```{r check-emmeans}
# full data frame with all means and CIs 
yield5 %>% 
  mutate(emm2 = map(emmeans, data.frame)) %>% 
  unnest(emm2) #
#You can filter and make a data frame for each population and rate
```


```{r cld-function}
cld_function <- function(emmeans) {
  if(requireNamespace("multcomp")) {
    multcomp::cld(emmeans, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE)
}
}
```


```{r cld}
yield6 <- yield5 %>% 
  mutate(cld = map(emmeans, cld_function))
```


```{r}
# here is similar to emmeans but you have letters
yield7 <- yield6 %>% 
  unnest(cld)
# You can also filter and make specific data frames
yield7
```

```{r}
yield7 %>% 
  ggplot(aes(x = post, y = emmean)) +
  geom_point() +
#  geom_label(aes(label = .group), parse = TRUE, # somthing is wrong with geom_text
#            nudge_x = 0,
#            nudge_y = -0.3) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.1) +
  facet_grid(~ site, scales = "free") +
  coord_flip() +
#  scale_x_reordered() +
  scale_y_continuous("Yield", limits = c(2000, 6000),
                     labels = scales::label_number(scale = 1)) +
  theme_bw()
# this is how you reorder by high to low. Notice that all rates follow same pattern.
```